#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Jan 31, 2020 08:54:29 PM CET  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+361+135
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1265 877
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -background #ccffd6 -height 465 -width 25 
    vTcl:DefineAlias "$top.fra43" "bordercolorFrame1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra45 \
        -borderwidth 2 -background #ccffd6 -height 465 -width 35 
    vTcl:DefineAlias "$top.fra45" "bordercolorFrame2" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra46 \
        -borderwidth 2 -background #ccffd6 -height 25 -width 615 
    vTcl:DefineAlias "$top.fra46" "bordercolorFrame3" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra47 \
        -borderwidth 2 -background #ccffd6 -height 25 -width 615 
    vTcl:DefineAlias "$top.fra47" "bordercolorFrame4" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra48 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 35 -width 135 
    vTcl:DefineAlias "$top.fra48" "HeaderFrame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra48
    label $site_3_0.lab49 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {SQL Tuple Generator} 
    vTcl:DefineAlias "$site_3_0.lab49" "HeaderLabel" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab49 \
        -in $site_3_0 -x 5 -y 10 -width 126 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra50 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 115 -width 555 
    vTcl:DefineAlias "$top.fra50" "tipusSentenciaFrame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra50
    label $site_3_0.lab51 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Quina sentencia vols crear?} 
    vTcl:DefineAlias "$site_3_0.lab51" "pregunta1Label" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad52 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {CREATE TABLE} -value 1 
    vTcl:DefineAlias "$site_3_0.rad52" "CreateTableRad" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad53 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {ALTER TABLE} -value 2 
    vTcl:DefineAlias "$site_3_0.rad53" "AlterTableRad" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad54 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {INSERT INTO} -value 3 
    vTcl:DefineAlias "$site_3_0.rad54" "InserIntoRad" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab51 \
        -in $site_3_0 -x 10 -y 0 -width 166 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad52 \
        -in $site_3_0 -x 10 -y 20 -width 111 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad53 \
        -in $site_3_0 -x 140 -y 20 -width 111 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad54 \
        -in $site_3_0 -x 10 -y 50 -width 105 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x -9 -y -10 -width 25 -relwidth 0 -height 465 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra45 \
        -in $top -x 583 -y -10 -width 35 -relwidth 0 -height 465 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x -10 -y -9 -width 615 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x -10 -y 435 -width 615 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 230 -y 5 -width 135 -relwidth 0 -height 35 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra50 \
        -in $top -x 30 -y 50 -width 555 -relwidth 0 -height 115 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

